### ISSUE TITLE
Старайся не усложнять, где нет необходимости.

### ISSUE THREAD

**Issue by DmitriyPavlovskyi** [AlexandrMoroz/beetroot-hw#1]
https://github.com/AlexandrMoroz/beetroot-hw/blob/fcf7dd10ce2e5e840b66dfdc872ac829ba85876a/1%20lesson/1hw/index.html#L52

Старайся не усложнять, где нет необходимости. Для этой задачи нет особой необходимости использовать конструктор и классы. Всегда, когда есть есть выбор написать более простой и читаемый код, старайся делать выбор в эту сторону

**Comment by AlexandrMoroz** [comment]
Исправил
