### ISSUE TITLE
 Зачем нужен этот метод, если он не используется?

### ISSUE THREAD

**Issue by DmitriyPavlovskyi** [AlexandrMoroz/beetroot-hw#2]
https://github.com/AlexandrMoroz/beetroot-hw/blob/fcf7dd10ce2e5e840b66dfdc872ac829ba85876a/1%20lesson/1hw/index.html#L45-L47

 Зачем нужен этот метод, если он не используется?

**Comment by AlexandrMoroz** [comment]
Удалил
