### ISSUE TITLE
Сортировка не отработала

### ISSUE THREAD

**Issue by DmitriyPavlovskyi** [AlexandrMoroz/beetroot-hw#3]
https://github.com/AlexandrMoroz/beetroot-hw/blob/fcf7dd10ce2e5e840b66dfdc872ac829ba85876a/1%20lesson/1hw/index.html#L54
![image](https://user-images.githubusercontent.com/15727253/87233827-9eebf100-c3d3-11ea-9833-cd557f39ff26.png)
Судя по всему, сортировка не отработала правильно. Посмотри вот тут про метод .sort() и что можно дополнительно с ним сделать https://learn.javascript.ru/array-methods

**Comment by AlexandrMoroz** [comment]
Исправил
